### ISSUE TITLE
Worthless quickbar replacement breaks all quickbar mods by loading after the OG quickbar

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [JamesTheMaker/Community-Framework#1]
title says everything.

Install StardustCore, then this framework. your new, useless quickbar doesn't even work. throws errors when you click any buttons, and generally unusable.

....fuck you for forcing this on us...

Here's a snippet from my game logs for you to gawk at.

`[16:38:26.747] [Error] Exception while calling script init: (LuaException) Error code 2, [string "/interface/scripted/cf_unibar/quickbarprepatc..."]:5: attempt to index a function value (global 'condition')
stack traceback:
	[C]: in metamethod '__index'
	[string "/interface/scripted/cf_unibar/quickbarprepatc..."]:5: in global 'condition'
	[string "/interface/scripted/cf_unibar/quickbarprepatc..."]:37: in global 'populateLists'
	[string "/interface/scripted/cf_unibar/cf_unibar.lua"]:14: in upvalue 'originalInit'
	[string "/interface/scripted/mmupgrade/sb_mmupgradegui..."]:11: in function <[string "/interface/scripted/mmupgrade/sb_mmupgradegui..."]:11>
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x2e5) [0xcd6ea5]
./starbound(_ZN4Star12LuaExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x6c) [0xc6ce2c]
./starbound() [0xa16247]
./starbound(_ZN4Star9LuaEngine12callFunctionIJEEENS_7VariantINS2_INS_5EmptyEJbxdNS_9LuaStringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_11LuaVariadicIS9_EEEEEiDpRKT_+0x94) [0xfb0424]
./starbound(_ZNK4Star10LuaContext10invokePathINS_7VariantINS_5EmptyEJbxdNS_9LuaStringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJEEET_RKNS_6StringEDpRKT0_+0xd8) [0x1619cc8]
./starbound(_ZN4Star16LuaBaseComponent4initEv+0x125) [0x1618f65]
./starbound(_ZN4Star14BaseScriptPane9displayedEv+0x2ea) [0x183d28a]
./starbound(_ZN4Star10ScriptPane9displayedEv+0x188) [0x1938568]
./starbound(_ZN4Star11PaneManager11displayPaneENS_9PaneLayerERKSt10shared_ptrINS_4PaneEESt8functionIFvS6_EE+0x164) [0x17de344]
./starbound(_ZN4Star21RegisteredPaneManagerINS_18MainInterfacePanesEE21displayRegisteredPaneERKS1_+0x1d5) [0x18ba9a5]
./starbound(_ZN4Star21RegisteredPaneManagerINS_18MainInterfacePanesEE20toggleRegisteredPaneERKS1_+0x55) [0x18e50b5]
./starbound(_ZN4Star13MainInterface12overlayClickERKNS_6VectorIiLm2EEENS_11MouseButtonE+0x395) [0x18d04f5]
./starbound(_ZN4Star13MainInterface16handleInputEventERKNS_7VariantINS_12KeyDownEventEJNS_10KeyUpEventENS_14TextInputEventENS_14MouseMoveEventENS_20MouseButtonDownEventENS_18MouseButtonUpEventENS_15MouseWheelEventENS_19ControllerAxisEventENS_25ControllerButtonDownEventENS_23ControllerButtonUpEventEEEE+0x55e) [0x18d0c7e]
./starbound(_ZN4Star17ClientApplication12processInputERKNS_7VariantINS_12KeyDownEventEJNS_10KeyUpEventENS_14TextInputEventENS_14MouseMoveEventENS_20MouseButtonDownEventENS_18MouseButtonUpEventENS_15MouseWheelEventENS_19ControllerAxisEventENS_25ControllerButtonDownEventENS_23ControllerButtonUpEventEEEE+0x11a) [0x19657ba]
./starbound(_ZN4Star11SdlPlatform3runEv+0x248) [0x1724088]
./starbound(_ZN4Star18runMainApplicationESt10unique_ptrINS_11ApplicationESt14default_deleteIS1_EENS_10StringListE+0x189) [0x171b4f9]
./starbound(main+0x29c) [0xb645dc]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x23850) [0x7f903974c850]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8a) [0x7f903974c90a]
./starbound(_start+0x2e) [0xb64bce]
`

...please, for the love of god, DO NOT DO SHIT LIKE THIS. Make your quickbar separate from the libraries of this framework, lest you break the shit that needs OG quickbar AND a library from this framework.

Or ignore me, don't care. i'm just an angry player that one day woke up to a broken mods list because some idiot decided to replace quickbar with his unfinished prototype and consequently break every fucking mod on the workshop that uses it.

**Comment by Emmaker** [comment]
I understand, and I have listened. I have since announced in my Discord, and have updated the mod on Steam, that the Unibar will be retired and replaced with Quickbar, with my own faster code. I apologize for the Unibar, it was a callous experiment on my part and I've since discovered that I never really wanted a full replacement to the Quickbar, just faster and better code (because the old code is god awful)

**Comment by VideoGames1000** [comment]
The ongoing issues and steam comments make me think it might be time to give this issue further consideration.
Been meaning to go through Stardust Lite's code and see if I can't use that to help unshit the existing quickbar implementation but I keep not getting around to it.

**Comment by Emmaker** [comment]
There's nothing wrong with the Quickbar implementation. It functions perfectly as intended, and is fully compatible with all past and future icons.
