### ISSUE TITLE
FU SAIL incompatibility

### ISSUE THREAD

**Issue by Polk-O-Tech** [JamesTheMaker/Community-Framework#3]
The quickbar SAIL calls the vanilla SAIL ("OpenAiInterface"), not the FU one ("ScriptPane", "/interface/ai/fu_byosai.config")
-> we get the FU failsafe SAIL

For reference i attached the shit patch i made that simply replaces it, but would obviously not work if FU is not installed.

[CommunityFramework_FU.zip](https://github.com/user-attachments/files/16927525/CommunityFramework_FU.zip)

**Comment by Emmaker** [comment]
This is technically intended behavior, as the icon targets "OpenAiInterface" rather than "ScriptPane" as the vanilla SAIL (or "failsafe" SAIL, in Ztarbound's case) is hardcoded. 

I could implement support rather easily, but that would set a precedent for adding built-in support for other mods that might be adversely affected by CF, so I'm in the process of internally debating whether it's worth it or not.

**Comment by Polk-O-Tech** [comment]
Personally I can't really understand your objections. As a user I find it strange that a "framework" mod would require a patch for one of the most used mods of the game. (Also it feels incredibly silly to make people download a patch for what is likely to be 2 lines of code.)

More generally, while I can see why you'd rather not patch for other mods, high levels of/ideally universal compatibility is in my opinion an intrinsic part of what makes a "community framework.

I'm aware this bug isn't game breaking, but it's still far from seamless and it just feels so unnecessary.

**Comment by Emmaker** [comment]
Again, this isn't a "bug", this is intended behavior.

Also, Frackin' Universe is also another beast of an issue. The mod's questionable development history, quality, and developers make it not worth supporting in general in my eyes.

**Comment by Polk-O-Tech** [comment]
Okay, i can understand not being willing to spend time on patching for a mod you don't use. I still think it's silly, but whatever.
In that case I'll see about learning more lua and then either make a PR/patch, if you'd rather not merge it.

Do you perchance know of a convenient way too check whether another mod is installed in lua?

**Comment by Emmaker** [comment]
In Starbound, the best way to do that is to retrieve a file with `root.assetJson` that only exists with that mod and test if it has any value (just use it like a boolean value).
